### ISSUE TITLE
Recipes broken (1.16)

### ISSUE THREAD

**Issue by ivan-petrovic-soprex** [jexline/exline-mods-issues#1]
three recipes for rolls are broken, specifying bad item ids instead of saying "sushimod:cooked_rice"

more importantly, this mod doesn't play well with other mods which also add rice, for example farmer's delight which almost everyone has installed.

steps to fix: 
step 1
in /data/forge/tags/items/grain create a file   rice.json     with the following structure:
{
  "replace": false,
  "values": [
    "sushimod:cooked_rice"
  ]
}

step 2:
edit all roll/sashimi recipes to use   forge:grain/rice   as rice. for example:
{
    "type": "minecraft:crafting_shapeless",
    "ingredients": [
        {
            "tag": "forge:grain/rice"
        },
        {
            "tag": "forge:grain/rice"
        },
        {
            "tag": "forge:grain/rice"
        },
        {
            "item": "sushimod:nori"
        },
        {
            "item": "sushimod:cucumber"
        },
        {
            "item": "minecraft:carrot"
        },
        {
            "item": "minecraft:salmon"
        }
   ],
    "result": {
        "item": "sushimod:salmon_roll"
    }
}

done. now we don't have to farm second kind of rice.

**Comment by jexline** [comment]
I am sorry I have not fixed this yet, I am back and will get to it soon.

**Comment by jexline** [comment]
ok, mr smarty pants. here you go
