### ISSUE TITLE
[1.18.1][CopperEquipment]Parsing error

### ISSUE THREAD

**Issue by drakray** [jexline/exline-mods-issues#11]
latest.log>
```
[...]
Line 1709: [12:27:13] [Server thread/ERROR]: Parsing error loading recipe copperequipment:copper_helm_smelt
[...]
Line 1768: [12:27:15] [Server thread/ERROR]: Parsing error loading custom advancement copperequipment:recipes/misc/copper_pickaxe: Unknown item id 'minecraft:copper_pick'
[...]
```

Minecraft 1.18.1
Forge 88
Copper Equipment 2.0.0
buncha other mods

**Comment by xanthian** [comment]
Yep same.
`Parsing error loading recipe copperequipment:copper_helm_smelt
 com.google.gson.JsonSyntaxException: Unknown item 'copperequipment:copper_helm'`
 
 Should be `copperequipment:copper_helmet`

`Parsing error loading custom advancement copperequipment:recipes/misc/copper_pickaxe: Unknown item id 'minecraft:copper_pick'`

should be `copperequipment:copper_pickaxe`

**Comment by jexline** [comment]
This will be updated in v2.0.2 for 1.18.2 and should be up by tomorrow. I will fix other versions in time.
