### ISSUE TITLE
Same mod id as another.

### ISSUE THREAD

**Issue by xanthian** [jexline/exline-mods-issues#12]
https://www.curseforge.com/minecraft/mc-mods/copper-equipment-fabric

Not that both mods would be installed at the same time, but bad practice to have the same ID.

**Comment by jexline** [comment]
Did not know of this mod, but can make a change to the id in the next update so it can be compatible.

**Comment by K0-RR** [comment]
I hate when mods use so generic ids.
Imagine you found a bug, or maybe your game is crashing and all it is in the log is copperequipment:coppersword. No problem, I will just open the modmenu and click on the issues button, on wait they [didn't fill in the contact info or they left the ones from the Fabric Example Mod template](https://github.com/issues?q=is%3Aissue+author%3ARDKRACZ+missing+issues+tag).
You go to the CF and try to guess which one of the 13 copper tools mod your modpack is using.
If the id would be e.g. exlinecoppereq or jexline-copperequipment I could just look at the creator's username.

**Comment by xanthian** [comment]
> Did not know of this mod, but can make a change to the id in the next update so it can be compatible.

just a warning, changing the id would remove any items with the old id from players worlds.

**Comment by jexline** [comment]
I do not think people will be too worried about their old tools, as copper is fairly easy to find. I am making the id 'exlinecopperequipment' in the next update. This should make it compatible with other mods and avoid other possible issues. I did not know there were so many other copper mods, but should have know. I will be uploading the new files today.
