### ISSUE TITLE
exlinecopperequipment:recipes/misc/copper_pickaxe advancement refers to "minecraft:copper_pick" instead of "exlinecopperequipment:copper_pick"

### ISSUE THREAD

**Issue by dragonmaus** [jexline/exline-mods-issues#23]
This causes the advancement to fail to register, meaning that you do not unlock the associated recipes when you have a copper pick in your inventory.

**Comment by dragonmaus** [comment]
(This issue expands on #20)

**Comment by jexline** [comment]
this issue should be fixed in the latest release for 1.18.2, Also part of issue #20 is resolved now, sorry this took so long!
